import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

/**
 * A sample paper, generated as a real PDF and run through the real pipeline.
 *
 * It is written here rather than shipped as a fixture so that it is unambiguously
 * ours: no real author is misattributed, and nothing is presented as a genuine
 * published result. The content is a plausible but clearly-labelled illustration.
 */

const TITLE = 'Sleep Duration and Recovery in Endurance Athletes';
const AUTHORS = 'A. Rivera, K. Osei, M. Lindqvist';
const AFFIL = 'Sample Document — generated by Paper Animator to demonstrate extraction';

interface Block {
  kind: 'h1' | 'h2' | 'body' | 'caption' | 'label';
  text: string;
}

const ABSTRACT = `Abstract — Sleep is widely believed to influence physical recovery, but controlled evidence in trained populations remains limited. We conducted a randomised crossover study in which 62 endurance athletes completed two four-week blocks under extended (9.0 h) and habitual (7.1 h) sleep opportunity. Recovery was assessed by time to return to baseline power output following a standardised depletion protocol. Extended sleep reduced recovery time by 31.4% (95% CI 24.8-37.9, p < .001) relative to habitual sleep. Perceived exertion was lower in the extended condition (mean difference 1.2 +/- 0.4 points, p = .003), while maximal power output did not differ between conditions. The effect persisted at twelve months in the 41 participants who completed follow-up. These results suggest that sleep extension is associated with faster recovery, though the mechanism remains unclear and the sample was drawn from a single training centre.`;

const BODY: Block[] = [
  { kind: 'h1', text: '1. Introduction' },
  {
    kind: 'body',
    text: 'Recovery between training sessions determines how much load an athlete can tolerate over a season. Coaches have long treated sleep as a lever for recovery, yet the question of whether extending sleep opportunity produces a measurable change in recovery time has rarely been tested under controlled conditions. Observational work reports associations between habitual sleep duration and self-reported readiness, but such designs cannot separate sleep from the training and lifestyle factors that accompany it.',
  },
  {
    kind: 'body',
    text: 'We ask whether extending nightly sleep opportunity shortens the time required to return to baseline power output after a standardised depletion protocol. A crossover design allows each athlete to serve as their own control, removing between-subject variation in fitness and training history that has complicated earlier work.',
  },
  { kind: 'h1', text: '2. Methods' },
  {
    kind: 'body',
    text: 'We recruited 62 endurance athletes (n = 62, 34 female) from a single regional training centre. Participants completed two four-week blocks in randomised order, separated by a two-week washout. In the extended condition, participants were given a 9.0 h sleep opportunity; in the habitual condition, 7.1 h. Sleep was measured by wrist actigraphy and confirmed by daily diary.',
  },
  {
    kind: 'body',
    text: 'At the end of each block, participants completed a depletion protocol consisting of repeated maximal efforts until power output fell below 70% of baseline. Recovery time was defined as the interval until power output returned to within 2% of the pre-protocol baseline, measured every six hours. All analyses were pre-registered.',
  },
  { kind: 'h1', text: '3. Results' },
  {
    kind: 'body',
    text: 'Extended sleep reduced recovery time by 31.4% (95% CI 24.8-37.9, p < .001) compared with habitual sleep. Mean recovery time was 28.6 h in the extended condition and 41.7 h in the habitual condition. Figure 1 shows the distribution of recovery times across both conditions.',
  },
  {
    kind: 'body',
    text: 'Perceived exertion during the depletion protocol was lower under extended sleep (mean difference 1.2 +/- 0.4 points on a 10-point scale, p = .003). Maximal power output did not differ significantly between conditions (p = .41), indicating that the effect was specific to recovery rather than performance capacity. Table 1 reports the primary and secondary outcomes.',
  },
  {
    kind: 'body',
    text: 'The effect persisted at twelve months in the 41 participants who completed voluntary follow-up, with a 27.9% reduction in recovery time (95% CI 19.4-36.1) among those who maintained extended sleep.',
  },
  { kind: 'h1', text: '4. Discussion' },
  {
    kind: 'body',
    text: 'These results suggest that sleep extension is associated with faster physical recovery in trained endurance athletes. The magnitude of the effect is larger than previously reported in observational work, which may reflect the controlled sleep opportunity rather than measured sleep duration.',
  },
  {
    kind: 'body',
    text: 'The mechanism remains unclear. We did not measure hormonal markers, so we cannot rule out that the effect operates through pathways other than sleep itself, such as reduced daytime activity in the extended condition.',
  },
  { kind: 'h1', text: '5. Limitations' },
  {
    kind: 'body',
    text: 'Participants were drawn from a single training centre, and may not generalise to recreational athletes or to other sports. Sleep opportunity was prescribed rather than achieved, and actigraphy overestimates sleep in active populations. The follow-up sample was self-selected, so the twelve-month estimate should be treated as exploratory. Further work is needed to establish whether the effect holds in older athletes.',
  },
  { kind: 'h1', text: '6. Conclusion' },
  {
    kind: 'body',
    text: 'In conclusion, extending sleep opportunity from 7.1 to 9.0 hours reduced recovery time by roughly a third in trained endurance athletes, without changing maximal power output. Sleep extension appears to be a low-cost intervention for athletes managing high training loads.',
  },
  { kind: 'h1', text: 'References' },
  {
    kind: 'body',
    text: '[1] Osei K., Lindqvist M. Sleep and athletic performance: a review of controlled trials. Journal of Sport Science, 2021.',
  },
  {
    kind: 'body',
    text: '[2] Rivera A. Actigraphy in active populations: measurement error and its consequences. Sleep Methods, 2019.',
  },
  {
    kind: 'body',
    text: '[3] Tanaka H., Whitfield P. Recovery kinetics after repeated maximal effort. Applied Physiology Reports, 2020.',
  },
];

export async function buildSamplePaper(): Promise<File> {
  const pdf = await PDFDocument.create();
  pdf.setTitle(TITLE);
  pdf.setAuthor(AUTHORS);
  pdf.setSubject('Sample document generated by Paper Animator');

  const serif = await pdf.embedFont(StandardFonts.TimesRoman);
  const serifBold = await pdf.embedFont(StandardFonts.TimesRoman);
  const bold = await pdf.embedFont(StandardFonts.TimesRomanBold);
  const italic = await pdf.embedFont(StandardFonts.TimesRomanItalic);

  const W = 595.28;
  const H = 841.89;
  const MARGIN = 56;
  const COL_GAP = 22;
  const COL_W = (W - MARGIN * 2 - COL_GAP) / 2;
  const INK = rgb(0.11, 0.11, 0.12);

  let page = pdf.addPage([W, H]);
  let col = 0;
  let y = H - MARGIN;
  // Page one's columns begin beneath the full-width front matter, not at the
  // top of the sheet — otherwise the second column runs up beside the title.
  let columnTop = H - MARGIN;

  const newPage = () => {
    page = pdf.addPage([W, H]);
    col = 0;
    columnTop = H - MARGIN;
    y = columnTop;
  };

  const nextColumn = () => {
    if (col === 0) {
      col = 1;
      y = columnTop;
    } else {
      newPage();
    }
  };

  const colX = () => MARGIN + col * (COL_W + COL_GAP);

  const ensure = (needed: number) => {
    if (y - needed < MARGIN) nextColumn();
  };

  /* ---- front matter, full width ---- */
  const titleLines = wrap(TITLE, bold, 19, W - MARGIN * 2);
  for (const line of titleLines) {
    page.drawText(line, { x: MARGIN, y: y - 19, size: 19, font: bold, color: INK });
    y -= 24;
  }
  y -= 8;
  page.drawText(AUTHORS, { x: MARGIN, y: y - 11, size: 11, font: serif, color: rgb(0.25, 0.25, 0.27) });
  y -= 16;
  page.drawText(AFFIL, { x: MARGIN, y: y - 9, size: 8.5, font: italic, color: rgb(0.45, 0.45, 0.47) });
  y -= 22;
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: W - MARGIN, y },
    thickness: 0.6,
    color: rgb(0.78, 0.78, 0.79),
  });
  y -= 20;

  /* ---- abstract, full width ---- */
  for (const line of wrap(ABSTRACT, serif, 9.4, W - MARGIN * 2)) {
    page.drawText(line, { x: MARGIN, y: y - 9.4, size: 9.4, font: serif, color: INK });
    y -= 13.2;
  }
  y -= 16;

  columnTop = y;
  const drawInColumn = (blocks: Block[]) => {
    for (const block of blocks) {
      if (block.kind === 'h1') {
        ensure(34);
        y -= 8;
        page.drawText(block.text, { x: colX(), y: y - 11, size: 11, font: bold, color: INK });
        y -= 19;
        continue;
      }
      const size = block.kind === 'caption' ? 8.2 : 9.2;
      const font = block.kind === 'caption' ? italic : serif;
      const lines = wrap(block.text, font, size, COL_W);
      for (const line of lines) {
        ensure(size + 4);
        page.drawText(line, { x: colX(), y: y - size, size, font, color: INK });
        y -= size * 1.42;
      }
      y -= 6;
    }
  };

  // Reset to column layout beneath the abstract.
  y = columnTop;
  col = 0;

  // Split the body so a figure and a table land in sensible places.
  const beforeFigure = BODY.slice(0, 8);
  const afterFigure = BODY.slice(8);

  drawInColumn(beforeFigure);

  /* ---- Figure 1: a real chart, drawn with vectors ---- */
  ensure(150);
  const figX = colX();
  const figTop = y - 6;
  const figH = 104;
  const figW = COL_W;

  page.drawRectangle({
    x: figX,
    y: figTop - figH,
    width: figW,
    height: figH,
    color: rgb(1, 1, 1),
  });

  const axisY = figTop - figH + 22;
  const axisX = figX + 26;
  page.drawLine({
    start: { x: axisX, y: axisY },
    end: { x: figX + figW - 6, y: axisY },
    thickness: 0.7,
    color: rgb(0.35, 0.35, 0.37),
  });
  page.drawLine({
    start: { x: axisX, y: axisY },
    end: { x: axisX, y: figTop - 8 },
    thickness: 0.7,
    color: rgb(0.35, 0.35, 0.37),
  });

  const bars = [
    { label: 'Ext', v: 0.42, accent: true },
    { label: 'Hab', v: 0.92, accent: false },
  ];
  const barW = 34;
  bars.forEach((b, i) => {
    const bx = axisX + 22 + i * (barW + 30);
    const bh = b.v * (figTop - 16 - axisY);
    page.drawRectangle({
      x: bx,
      y: axisY,
      width: barW,
      height: bh,
      color: b.accent ? rgb(0.14, 0.33, 0.62) : rgb(0.62, 0.62, 0.64),
    });
    page.drawText(b.label, {
      x: bx + 8,
      y: axisY - 11,
      size: 7.5,
      font: serif,
      color: rgb(0.35, 0.35, 0.37),
    });
  });
  page.drawText('h', { x: axisX - 12, y: figTop - 20, size: 7.5, font: serif, color: rgb(0.4, 0.4, 0.42) });
  page.drawText('50', { x: axisX - 18, y: axisY + 52, size: 7, font: serif, color: rgb(0.5, 0.5, 0.52) });
  page.drawText('0', { x: axisX - 12, y: axisY - 2, size: 7, font: serif, color: rgb(0.5, 0.5, 0.52) });

  y = figTop - figH - 8;
  drawInColumn([
    {
      kind: 'caption',
      text: 'Figure 1. Mean recovery time under extended (Ext) and habitual (Hab) sleep opportunity. Error bars omitted for clarity.',
    },
  ]);

  drawInColumn(afterFigure.slice(0, 3));

  /* ---- Table 1: a real ruled table ---- */
  ensure(120);
  const tabTop = y - 4;
  const rows = [
    ['Outcome', 'Extended', 'Habitual', 'p'],
    ['Recovery time (h)', '28.6', '41.7', '<.001'],
    ['Perceived exertion', '5.4', '6.6', '.003'],
    ['Max power (W)', '384', '381', '.41'],
    ['Sleep (h)', '8.6', '7.1', '<.001'],
  ];
  const rowH = 15;
  const colXs = [colX(), colX() + 92, colX() + 138, colX() + 184];

  rows.forEach((row, r) => {
    const ry = tabTop - r * rowH;
    row.forEach((cell, c) => {
      page.drawText(cell, {
        x: colXs[c],
        y: ry - 9,
        size: 8.2,
        font: r === 0 ? bold : serif,
        color: INK,
      });
    });
    if (r === 0) {
      page.drawLine({
        start: { x: colX(), y: ry - 12.5 },
        end: { x: colX() + COL_W - 4, y: ry - 12.5 },
        thickness: 0.6,
        color: rgb(0.4, 0.4, 0.42),
      });
    }
  });
  page.drawLine({
    start: { x: colX(), y: tabTop + 4 },
    end: { x: colX() + COL_W - 4, y: tabTop + 4 },
    thickness: 0.8,
    color: rgb(0.3, 0.3, 0.32),
  });
  page.drawLine({
    start: { x: colX(), y: tabTop - rows.length * rowH + 3 },
    end: { x: colX() + COL_W - 4, y: tabTop - rows.length * rowH + 3 },
    thickness: 0.8,
    color: rgb(0.3, 0.3, 0.32),
  });

  y = tabTop - rows.length * rowH - 8;
  drawInColumn([
    {
      kind: 'caption',
      text: 'Table 1. Primary and secondary outcomes by condition. Values are means. p-values from paired t-tests.',
    },
  ]);

  drawInColumn(afterFigure.slice(3));

  void serifBold;

  const bytes = await pdf.save();
  const blob = new Blob([bytes as BlobPart], { type: 'application/pdf' });
  return new File([blob], 'sample-sleep-and-recovery.pdf', { type: 'application/pdf' });
}

function wrap(
  text: string,
  font: { widthOfTextAtSize: (t: string, s: number) => number },
  size: number,
  maxWidth: number,
): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = '';
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}
