import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage({ viewport: { width: 1500, height: 950 }, deviceScaleFactor: 2 });
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR: ' + e.message));
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
await page.goto('http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
await page.getByRole('button', { name: /Switch to the dark Press appearance/ }).click();
await page.waitForTimeout(900);
await page.screenshot({ path: 'shots/60-press-landing.png' });
await page.getByRole('button', { name: 'Try a sample paper' }).first().click();
await page.waitForSelector('.pa-reader', { timeout: 40000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'shots/61-press-setup.png' });
await page.waitForTimeout(1800);
const skip = page.getByRole('button', { name: 'Skip' }).first();
if (await skip.count()) await skip.click();
await page.waitForTimeout(500);
await page.screenshot({ path: 'shots/62-press-editor.png' });
console.log(errors.length ? 'CONSOLE ERRORS:\n' + errors.slice(0, 8).join('\n') : 'no console errors');
await browser.close();
